- hosts: all
  tasks:
    - name: Turn off selinux
      selinux:
        state: disabled

    - name: Disable systemd services
      service:
        name: "{{ item }}"
        enabled: no
        state: stopped
      loop:
        - firewalld
        - NetworkManager

    - name: Load br_netfilter
      modprobe:
        name: br_netfilter
        state: present
    - name: Load br_netfilter at boot
      copy:
        owner: root
        group: root
        mode: "0644"
        dest: /etc/modules-load.d/kubernetes.conf
        content:
          br_netfilter
    - name: Change sysctl setting
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

    # https://github.com/kubernetes-retired/contrib/blob/master/ansible/roles/node/tasks/swapoff.yml
    - name: Turn off swap mount
      mount:
        name: swap
        fstype: swap
        state: absent
    - name: Turn off swap now
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes

    - include_tasks: mariadb.yaml
      when: kubernetes_role == "master"
 
    - name: Install python packages for k8s module
      when: kubernetes_role == "master"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python2-openshift
        - python2-pyyaml

    - name: Prepare k8s spec file
      when: kubernetes_role == "master"
      delegate_to: localhost
      template:
        src: "{{ item }}"
        dest: "/tmp/{{ item | basename | splitext | first }}"
      loop:
        - templates/traefik.yaml.j2
        - templates/local-path-provisioner.yaml.j2
        - templates/onecloud-operator.yaml.j2
        - templates/onecloud-cluster.yaml.j2
    - name: Kubectl apply
      when: kubernetes_role == "master"
      k8s:
        src: "/tmp/{{ item | basename | splitext | first }}"
        state: present
      loop:
        - templates/traefik.yaml.j2
        - templates/local-path-provisioner.yaml.j2
        - templates/onecloud-operator.yaml.j2
        - templates/onecloud-cluster.yaml.j2
