---
- hosts: all
  vars:
    docker_yum_repo_url: https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    docker_install_compose: true
    docker_compose_version: 1.25.0
    docker_compose_path: /usr/bin/docker-compose
    the_package_state: present
    the_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  tasks:
    - include_role:
        name: geerlingguy.docker
    - package:
        name: "{{ item }}"
        state: "{{ the_package_state }}"
      with_items:
        - docker-ce
        - docker-ce-cli
    - user:
        name: "{{ the_user }}"
        append: yes
        groups:
          - docker
      when: "the_user != 'root'"
