- hosts: all
  tasks:
    - modprobe:
        name: br_netfilter
        state: present
    - sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        reload: yes
        state: present
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: geerlingguy.kubernetes
